mission_0: {
  waypoints:[ [40, 40, -20], [40, -40, -20], [-40, -40, -20], [-40, 40, -20] ],
  waypoints_velocity:[5, 5, 5, 5],
  }

mission_1: {
  waypoints:[ [60, 60, -30], [60, 20, -35], [20, 20, -30], [20, 60, -25] ],
  waypoints_velocity:[5, 5, 5, 5],
  }

mission_2: {
  waypoints:[ [-20, 60, -30], [-20, 20, -30], [-60, 20, -30], [-60, 60, -30] ],
  waypoints_velocity:[3, 3, 3, 3],
  }

mission_3: {
  waypoints:[ [-20, -60, -35], [-20, -20, -30], [-60, -20, -25], [-60, -60, -30] ],
  waypoints_velocity:[3, 5, 7, 5],
  }

mission_4: {
  waypoints:[ [60, -60, -30], [20, -60, -30], [60, -20, -30], [20, -20, -30] ],
  waypoints_velocity:[5, 3, 5, 5],
  }

mission_5: {
  waypoints:[ [20, -20, -40],[60, 20, -40], [60, -20, -40],  [20, 20, -40] ],
  waypoints_velocity:[5, 5, 5, 7],
  }

mission_6: {
  waypoints:[ [-20, 20, -40], [-20, -20, -40], [-60, -20, -40], [-60, 20, -40] ],
  waypoints_velocity:[5, 7, 3, 5],
  }

mission_7: {
  waypoints:[ [20, 60, -45], [-20, 20, -40],  [20, 20, -45], [-20, 60, -40] ],
  waypoints_velocity:[3, 5, 5, 7],
  }

mission_8: {
  waypoints:[ [20, -60, -40],  [-20, -60, -45], [-20, -20, -40],[20, -20, -40] ],
  waypoints_velocity:[5, 7, 7, 5],
  }

mission_9: {
  waypoints:[ [-40, 40, -65], [-40, -40, -55], [40, -40, -60], [40, 40, -60], [0, 0, -60]  ],
  waypoints_velocity:[3, 7, 7, 3, 5],
  }




